[package]
name = "http2-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
hpack = "0.3.0"
rustls-pemfile = "1"
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["full"]}
tokio-rustls = "0.24.1"
